savePrefix: ''

minimumReleaseAge: 2880 # 2 days in minutes
trustPolicy: no-downgrade
blockExoticSubdeps: true
strictDepBuilds: true # Might become default behavior in pnpm v11

allowBuilds:
  vite: true
  core-js: true
